# Generate and preview documentation on pull requests
# Posts a summary comment with key stats and links to preview
#
# Features:
# - Generates documentation for PR branches
# - Posts summary as PR comment
# - Uploads artifacts for download
# - Optional: Deploy to Netlify/Vercel for live preview

name: PR Documentation Preview

on:
  pull_request:
    branches: [main]

jobs:
  generate-preview:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Generate documentation
        id: generate
        run: |
          npx repomap generate --static --ci --output ./docs --format json
          
          # Extract stats from report.json
          PAGES=$(jq '.repositoryReports | map(.summary.totalPages) | add' ./docs/report.json)
          COMPONENTS=$(jq '.repositoryReports | map(.summary.totalComponents) | add' ./docs/report.json)
          GRAPHQL=$(jq '.repositoryReports | map(.summary.totalGraphQLOperations) | add' ./docs/report.json)
          
          echo "pages=$PAGES" >> $GITHUB_OUTPUT
          echo "components=$COMPONENTS" >> $GITHUB_OUTPUT
          echo "graphql=$GRAPHQL" >> $GITHUB_OUTPUT

      - name: Upload documentation artifact
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: ./docs
          retention-days: 7

      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            const pages = '${{ steps.generate.outputs.pages }}';
            const components = '${{ steps.generate.outputs.components }}';
            const graphql = '${{ steps.generate.outputs.graphql }}';
            
            const body = `## 📊 Documentation Preview
            
            | Metric | Count |
            |--------|-------|
            | 📄 Pages | ${pages} |
            | 🧩 Components | ${components} |
            | 🔗 GraphQL Operations | ${graphql} |
            
            ### 📥 Download
            
            Documentation artifacts are available in the [Actions tab](${context.payload.pull_request.html_url}/checks).
            
            ---
            *Generated by [repomap](https://github.com/wtdlee/repomap)*`;
            
            // Find existing comment
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });
            
            const botComment = comments.find(c => 
              c.user.type === 'Bot' && c.body.includes('📊 Documentation Preview')
            );
            
            if (botComment) {
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
                body,
              });
            } else {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body,
              });
            }

